/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg2410020169_uji;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import pkg2410020169_uji.mediaCRUD;
/**
 *
 * @author taufi
 */
public class mFrame extends javax.swing.JFrame {
    private String url ="jdbc:mysql://localhost:3306/2410020169_periklanan";
    private String user ="root";
    private String pass ="";
    
    private Connection KoneksiDatabase;
    private mainFrame mainFrame;
    /**
     * Creates new form mFrame
     */
    public mFrame(mainFrame mainFrame) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.mainFrame = mainFrame;
        
        try {
            Driver driverku = new com.mysql.jdbc.Driver();
            DriverManager.registerDriver(driverku);
            KoneksiDatabase = DriverManager.getConnection(url, user, pass);
            System.err.println("Frame Berhasil dikoneksikan ke database");
        } catch (Exception e) {
            System.err.println(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtNamed = new javax.swing.JTextField();
        txtJemed = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtMedia = new javax.swing.JTextField();
        txlabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nama Media");

        txtJemed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJemedActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Media");

        txtMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMediaActionPerformed(evt);
            }
        });

        txlabel3.setText("Jenis Media");

        jButton4.setText("Simpan Statment DBCRUD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("Simpan Prepared Statement Manual");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Simpan Prepareed Dari dbCRUD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Simpan Statement Manual");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setText("EDIT/UPDATE");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnHapus)
                                .addGap(9, 9, 9))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(txlabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamed)
                            .addComponent(txtJemed)
                            .addComponent(txtMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNamed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txlabel3)
                    .addComponent(txtJemed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addContainerGap(62, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)
                        .addGap(71, 71, 71))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJemedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJemedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJemedActionPerformed

    private void txtMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMediaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            String id_media = txtMedia.getText();
            String nama_media = txtNamed.getText();
            String jenis = txtJemed.getText();
            new mediaCRUD().SimpanMEDIAStatement(id_media,nama_media,jenis);
        } catch(Exception e){
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            String SimpanData = "INSERT INTO media (id_media, nama_media, jenis) VALUES (?, ?, ?)";
            Statement cekPrimaryKey = KoneksiDatabase.createStatement();
            ResultSet hasilcekPrimary = cekPrimaryKey.executeQuery("SELECT*FROM media WHERE id_media='"+txtMedia.getText()+"'");

            if (hasilcekPrimary.next()){
                JOptionPane.showMessageDialog(null,"Kode Primary Key sudah Terdaftar");
                hasilcekPrimary.close();
                cekPrimaryKey.close();
            } else {
                PreparedStatement perintahSimpan = KoneksiDatabase.prepareStatement(SimpanData);
                perintahSimpan.setString(1,txtMedia.getText());
                perintahSimpan.setString(2,txtNamed.getText());
                perintahSimpan.setString(3,txtJemed.getText());
                perintahSimpan.executeUpdate();

                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");

                perintahSimpan.close();
                hasilcekPrimary.close();
                cekPrimaryKey.close();
            }
        } catch (Exception e) {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new mediaCRUD().SimpanMEDIAPreparedstmt(txtMedia.getText(), txtNamed.getText(), txtJemed.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String id_media = txtMedia.getText();
            String nama_media = txtNamed.getText();
            String jenis = txtJemed.getText();
            String SQL = "INSERT INTO media (id_media, nama_media, jenis) VALUE('"+ id_media + "','" + nama_media + "','" + jenis + "')";

            Statement perintah = KoneksiDatabase.createStatement();
            ResultSet hasil = perintah.executeQuery("SELECT*FROM media WHERE id_media ='"+id_media+"'");

            if (hasil.next()){
                JOptionPane.showMessageDialog(null,"ID MEDIA sudah terdaftar");
                hasil.close();
                perintah.close();
            } else {
                perintah.executeUpdate(SQL);
                perintah.close();
                hasil.close();
                JOptionPane.showMessageDialog(null,"Data Berhasil disimpan");
            }
        } catch(Exception e){

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        mainFrame.setVisible(true); // Tampilkan kembali mainFrame
        this.dispose(); // Tutup pFrame
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
            // Ambil ID media dari field teks
            String id_media = txtMedia.getText();

            // Pastikan ID media tidak kosong
            if (id_media.isEmpty()) {
                JOptionPane.showMessageDialog(this, "ID media tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Query untuk menghapus data media berdasarkan ID
            String sqlHapus = "DELETE FROM media WHERE id_media = ?";
            PreparedStatement perintahHapus = KoneksiDatabase.prepareStatement(sqlHapus);
            perintahHapus.setString(1, id_media);

            int affectedRows = perintahHapus.executeUpdate(); // Eksekusi query

            // Cek apakah ada baris yang terpengaruh
            if (affectedRows > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "ID media tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
            }

            // Tutup PreparedStatement
            perintahHapus.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error saat menghapus data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
            // Ambil ID media dari field teks
            String id_media = txtMedia.getText();

            // Pastikan ID media tidak kosong
            if (id_media.isEmpty()) {
                JOptionPane.showMessageDialog(this, "ID media tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Ambil data baru dari field teks
            String nama_media = txtNamed.getText();
            String jenis = txtJemed.getText();
//            String nama_media = txtNapel.getText();
//            String gender = txtGender.getText();
//            String jenis = txtJemed.getText();

            // Query untuk mengupdate data media berdasarkan ID
            String sqlUpdate = "UPDATE media SET nama_media = ?, jenis = ? WHERE id_media = ?";
            PreparedStatement perintahUpdate = KoneksiDatabase.prepareStatement(sqlUpdate);
            perintahUpdate.setString(1, id_media);
            perintahUpdate.setString(2, nama_media);
            perintahUpdate.setString(3, jenis);

            int affectedRows = perintahUpdate.executeUpdate(); // Eksekusi query

            // Cek apakah ada baris yang terpengaruh
            if (affectedRows > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "ID media tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
            }

            // Tutup PreparedStatement
            perintahUpdate.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error saat mengupdate data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(mFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(mFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(mFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(mFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    /* Buat dan tampilkan mainFrame */
    mainFrame mainFrameInstance = new mainFrame(); // Buat instance mainFrame
    mainFrameInstance.setVisible(true); // Tampilkan mainFrame

    /* Buat dan tampilkan mFrame */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new mFrame(mainFrameInstance).setVisible(true); // Pass mainFrame instance ke mFrame
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txlabel3;
    private javax.swing.JTextField txtJemed;
    private javax.swing.JTextField txtMedia;
    private javax.swing.JTextField txtNamed;
    // End of variables declaration//GEN-END:variables
}
