/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg2410020169_uji;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import pkg2410020169_uji.pelangganCRUD;
/**
 *
 * @author taufi
 */
public class pFrame extends javax.swing.JFrame {
    private String url ="jdbc:mysql://localhost:3306/2410020169_periklanan";
    private String user ="root";
    private String pass ="";
    
    private Connection KoneksiDatabase;
    private mainFrame mainFrame;
    /**
     * Creates new form pFrame
     */
    public pFrame(mainFrame mainFrame) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.mainFrame = mainFrame;
        
        try {
            Driver driverku = new com.mysql.jdbc.Driver();
            DriverManager.registerDriver(driverku);
            KoneksiDatabase = DriverManager.getConnection(url, user, pass);
            System.err.println("Frame Berhasil dikoneksikan ke database");
        } catch (Exception e) {
            System.err.println(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        txtPelanggan = new javax.swing.JTextField();
        txlabel4 = new javax.swing.JLabel();
        txlabel3 = new javax.swing.JLabel();
        txtNapel = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nama Pelanggan");

        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Pelanggan");

        txtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatActionPerformed(evt);
            }
        });

        txtPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPelangganActionPerformed(evt);
            }
        });

        txlabel4.setText("Alamat");

        txlabel3.setText("Gender");

        jButton1.setText("Simpan Prepared Statement Manual");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Simpan Prepareed Dari dbCRUD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Simpan Statement Manual");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Simpan Statment DBCRUD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnEdit.setText("EDIT/UPDATE");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(txlabel3)
                            .addComponent(txlabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNapel)
                            .addComponent(txtGender)
                            .addComponent(txtPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlamat))
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addComponent(jButton3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEdit))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBack)))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHapus)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txlabel3)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txlabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEdit)
                        .addGap(19, 19, 19)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(btnBack))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatActionPerformed

    private void txtPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPelangganActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            String SimpanData = "INSERT INTO pelanggan (id_pelanggan, nama_pelanggan, gender, alamat) VALUES (?, ?, ?, ?)";
            Statement cekPrimaryKey = KoneksiDatabase.createStatement();
            ResultSet hasilcekPrimary = cekPrimaryKey.executeQuery("SELECT*FROM pelanggan WHERE id_pelanggan='"+txtPelanggan.getText()+"'");

            if (hasilcekPrimary.next()){
                JOptionPane.showMessageDialog(null,"Kode Primary Key sudah Terdaftar");
                hasilcekPrimary.close();
                cekPrimaryKey.close();
            } else {
                PreparedStatement perintahSimpan = KoneksiDatabase.prepareStatement(SimpanData);
                perintahSimpan.setString(1,txtPelanggan.getText());
                perintahSimpan.setString(2,txtNapel.getText());
                perintahSimpan.setString(3,txtGender.getText());
                perintahSimpan.setString(4,txtAlamat.getText());
                perintahSimpan.executeUpdate();

                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");

                perintahSimpan.close();
                hasilcekPrimary.close();
                cekPrimaryKey.close();
            }
        } catch (Exception e) {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new pelangganCRUD().SimpanPELANGGANPreparedstmt(txtPelanggan.getText(), txtNapel.getText(), txtGender.getText(), txtAlamat.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String id_pelanggan = txtPelanggan.getText();
            String nama_pelanggan = txtNapel.getText();
            String gender = txtGender.getText();
            String alamat = txtAlamat.getText();
            String SQL = "INSERT INTO pelanggan (id_pelanggan, nama_pelanggan, gender, alamat) VALUE('"+ id_pelanggan + "','" + nama_pelanggan + "','" + gender + "','" + alamat + "')";
            
            Statement perintah = KoneksiDatabase.createStatement();
            ResultSet hasil = perintah.executeQuery("SELECT*FROM pelanggan WHERE id_pelanggan ='"+id_pelanggan+"'");

            if (hasil.next()){
                JOptionPane.showMessageDialog(null,"ID PELANGGAN sudah terdaftar");
                hasil.close();
                perintah.close();
            } else {
                perintah.executeUpdate(SQL);
                perintah.close();
                hasil.close();
                JOptionPane.showMessageDialog(null,"Data Berhasil disimpan");
            }
        } catch(Exception e){

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            
            String id_pelanggan = txtPelanggan.getText();
            String nama_pelanggan = txtNapel.getText();
            String gender = txtGender.getText();
            String alamat = txtAlamat.getText();

            new pelangganCRUD().SimpanPELANGGANStatement(id_pelanggan,nama_pelanggan,gender,alamat);
        } catch(Exception e){
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        mainFrame.setVisible(true); // Tampilkan kembali mainFrame
        this.dispose(); // Tutup pFrame
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
        // Ambil ID pelanggan dari field teks
        String id_pelanggan = txtPelanggan.getText();
        
        // Pastikan ID pelanggan tidak kosong
        if (id_pelanggan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID Pelanggan tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Ambil data baru dari field teks
        String nama_pelanggan = txtNapel.getText();
        String gender = txtGender.getText();
        String alamat = txtAlamat.getText();

        // Query untuk mengupdate data pelanggan berdasarkan ID
        String sqlUpdate = "UPDATE pelanggan SET nama_pelanggan = ?, gender = ?, alamat = ? WHERE id_pelanggan = ?";
        PreparedStatement perintahUpdate = KoneksiDatabase.prepareStatement(sqlUpdate);
        perintahUpdate.setString(1, nama_pelanggan);
        perintahUpdate.setString(2, gender);
        perintahUpdate.setString(3, alamat);
        perintahUpdate.setString(4, id_pelanggan);

        int affectedRows = perintahUpdate.executeUpdate(); // Eksekusi query

        // Cek apakah ada baris yang terpengaruh
        if (affectedRows > 0) {
            JOptionPane.showMessageDialog(this, "Data berhasil diupdate!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "ID Pelanggan tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
        }

        // Tutup PreparedStatement
        perintahUpdate.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error saat mengupdate data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
       try {
        // Ambil ID pelanggan dari field teks
        String id_pelanggan = txtPelanggan.getText();
        
        // Pastikan ID pelanggan tidak kosong
        if (id_pelanggan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID Pelanggan tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Query untuk menghapus data pelanggan berdasarkan ID
        String sqlHapus = "DELETE FROM pelanggan WHERE id_pelanggan = ?";
        PreparedStatement perintahHapus = KoneksiDatabase.prepareStatement(sqlHapus);
        perintahHapus.setString(1, id_pelanggan);
        
        int affectedRows = perintahHapus.executeUpdate(); // Eksekusi query

        // Cek apakah ada baris yang terpengaruh
        if (affectedRows > 0) {
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "ID Pelanggan tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
        }

        // Tutup PreparedStatement
        perintahHapus.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error saat menghapus data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(pFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(pFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(pFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(pFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    /* Buat dan tampilkan mainFrame */
    mainFrame mainFrameInstance = new mainFrame(); // Buat instance mainFrame
    mainFrameInstance.setVisible(true); // Tampilkan mainFrame

    /* Buat dan tampilkan pFrame */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new pFrame(mainFrameInstance).setVisible(true); // Pass mainFrame instance ke pFrame
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txlabel3;
    private javax.swing.JLabel txlabel4;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtNapel;
    private javax.swing.JTextField txtPelanggan;
    // End of variables declaration//GEN-END:variables
}
